=== LeRoiDesKiwis/WebProject-cartoons/XML/cartoon.dtd
<!ELEMENT cartoon (informations, img, description, characters, seasons)>
<!ELEMENT informations (name, author, channel, first_diffusion, last_diffusion?)>

<!ENTITY % id "id ID #IMPLIED">

<!ENTITY % date
        "year CDATA #REQUIRED
        month CDATA #IMPLIED
        day CDATA #IMPLIED">

<!ELEMENT name (#PCDATA)>
<!ELEMENT author (#PCDATA)>
<!ELEMENT channel (#PCDATA)>
<!ELEMENT first_diffusion EMPTY>
<!ELEMENT last_diffusion EMPTY>

<!ELEMENT seasons (season+)>
<!ELEMENT season EMPTY>

<!ELEMENT description (#PCDATA)>

<!ELEMENT characters (character+)>
<!ELEMENT vo (#PCDATA)>
<!ELEMENT vf (#PCDATA)>
<!ELEMENT dub (vo, vf?)>
<!ELEMENT character (name, img, dub)>

<!ELEMENT img EMPTY>

<!ATTLIST name %id;>
<!ATTLIST channel %id;>
<!ATTLIST seasons %id;>
<!ATTLIST season %id;>
<!ATTLIST description %id;>
<!ATTLIST characters %id;>
<!ATTLIST character %id;>

<!ATTLIST img
        %id;
        href CDATA #REQUIRED
        src CDATA #REQUIRED>

<!ATTLIST season
        %id;
        season_number CDATA #REQUIRED
        number_of_episode CDATA #REQUIRED
        in_progress (yes|no) "no">

<!ATTLIST author
        %id;>

<!ATTLIST first_diffusion
        %id;
        %date;>

<!ATTLIST last_diffusion
        %id;
        %date;>

<!ATTLIST vf
        %id;>

<!ATTLIST vo
        %id;>

=== LeRoiDesKiwis/WebProject-cartoons/XML/amphibia.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE cartoon SYSTEM "cartoon.dtd">
<cartoon>
    <informations>
        <name>Amphibia</name>
        <author>Matt Braly</author>
        <channel>Disney Channel</channel>
        <first_diffusion year="2019"/>
        <last_diffusion year=""/>
    </informations>
    <img href="../Images/amphibia.jpg" src="https://wikidoublage.fandom.com/fr/wiki/Amphibia"/>
    <description>La série raconte les aventures d'une jeune fille américano-thaïlandaise de 13 ans nommée Anne Boonchuy.
        Après avoir volé une mystérieuse boîte à musique, elle est transportée par magie à Amphibia, un marais sauvage peuplé de grenouilles parlantes.
        Elle rencontre bientôt et se lie d'amitié avec une jeune grenouille aventureuse nommée Sprig Plantar,
        qui la guidera pour devenir un véritable héros tout en découvrant la première véritable amitié de sa vie</description>
    <characters>
        <character>
            <name>Anne Boonchuy</name>
            <img href="../Images/Anne_Boonchuy.png" src="https://amphibia.fandom.com/wiki/Anne_Boonchuy"/>
            <dub>
                <vo>Brenda Song</vo>
                <vf>Julia Khaye</vf>
            </dub>
        </character>
        <character>
            <name>Sprig Plantar</name>
            <img href="../Images/Sprig_Plantar.png" src="https://amphibia.fandom.com/wiki/Sprig_Plantar"/>
            <dub>
                <vo>Justin Felbinger</vo>
                <vf>Maxime Donnay</vf>
            </dub>
        </character>
        <character>
            <name>Marcy Wu</name>
            <img href="../Images/Marcy_Wu.png" src="https://amphibia.fandom.com/wiki/Marcy_Wu"/>
            <dub>
                <vo>Haley Tju</vo>
                <vf>Cathy Boquet</vf>
            </dub>
        </character>
    </characters>
    <seasons>
        <season season_number="1" number_of_episode="39"/>
        <season season_number="2" number_of_episode="36"/>
        <season season_number="3" number_of_episode="19" in_progress="yes"/>
    </seasons>
</cartoon>

=== LeRoiDesKiwis/WebProject-cartoons/XML/gumball.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE cartoon SYSTEM "cartoon.dtd">
<cartoon>
    <informations>
        <name>Le monde incroyable de Gumball</name>
        <author>Ben Bocquelet</author>
        <channel>Cartoon Network</channel>
        <first_diffusion year="2011" month="6" day="12"/>
        <last_diffusion year="2019" month="10" day="20"/>
    </informations>
    <img href="../Images/tawog.png" src="https://www.primevideo.com/detail/Amazing-World-of-Gumball/0GDR6GRJHLPDYJYXAEBOBMN7GL"/>
    <description>
        La série raconte la vie de Gumball Watterson, un chat bleu, âgé de 12 ans, et de Darwin,
        son poisson rouge acheté par ses parents qui deviendra son meilleur ami.
        Ils sont élèves dans la ville fictive d'Elmore. Ils se retrouvent souvent dans différentes situations surréalistes.
    </description>
    <characters>
        <character>
            <name>Gumball Watterson</name>
            <img href="../Images/gumball.png" src="https://theamazingworldofgumball.fandom.com/wiki/Gumball_Watterson"/>
            <dub>
                <vo>Jacob Hopkins</vo>
                <vf>Arthur Dubois</vf>
            </dub>
        </character>
        <character>
            <name>Darwin Watterson</name>
            <img href="../Images/darwin.png" src="https://theamazingworldofgumball.fandom.com/wiki/Darwin_Watterson"/>
            <dub>
                <vo>Kwesi Boakye</vo>
                <vf>Tim Belasri</vf>
            </dub>
        </character>
    </characters>
    <seasons>
        <season number_of_episode="36" season_number="1"/>
        <season number_of_episode="40" season_number="2"/>
        <season number_of_episode="40" season_number="3"/>
        <season number_of_episode="40" season_number="4"/>
        <season number_of_episode="40" season_number="5"/>
        <season number_of_episode="44" season_number="6"/>
    </seasons>
</cartoon>

=== LeRoiDesKiwis/WebProject-cartoons/XML/svtfoe.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE cartoon SYSTEM "cartoon.dtd">
<cartoon>
    <informations>
        <name>Star Vs The Forces Of Evil</name>
        <author>Daron Necfy</author>
        <channel>Disney Channel</channel>
        <first_diffusion year="2015" month="1" day="18"/>
        <last_diffusion year="2019" month="5" day="19"/>
    </informations>
    <img href="../Images/svtfoe.jpg" src="https://www.seriebox.com/serie/star-vs-forces-of-evil.html"/>
    <description>Star Butterfly est la princesse d'un royaume dans une autre dimension nommé Miouni.
        Elle fut envoyée sur Terre après avoir accidentellement ravagé son domicile avec sa nouvelle baguette magique,
        qu'elle ne maîtrise pas encore très bien. Arrivant donc dans la famille Diaz, elle se fait un nouveau meilleur ami du nom de Marco.
        Les deux héros essaieront alors d'avoir une vie normale, et en parallèle,
        de combattre le maléfique Ludo à travers les dimensions afin que la baguette de Star ne tombe pas entre ses mains.</description>
    <characters>
        <character>
            <name>Star Butterfly</name>
            <img href="" src=""/>
            <dub>
                <vo>Eden Sher</vo>
                <vf>Sophie Frison</vf>
            </dub>
        </character>
        <character>
            <name>Marco Diaz</name>
            <img href="../Images/Marco_Diaz.png" src="https://disney.fandom.com/wiki/Marco_Diaz"/>
            <dub>
                <vo>Adam McArthur</vo>
                <vf>Pierre Le Bec</vf>
            </dub>
        </character>
    </characters>
    <seasons>
        <season season_number="1" number_of_episode="24"/>
        <season season_number="2" number_of_episode="41"/>
        <season season_number="3" number_of_episode="38"/>
        <season season_number="4" number_of_episode="37"/>
    </seasons>
</cartoon>
